### ISSUE TITLE
Invalid base url for nyx api

### ISSUE THREAD

**Issue by mishl-dev** [SamirXR/Nyx-Bot#1]
https://github.com/SamirXR/Nyx-Bot/blob/661af3ebc3ab172611b8af555f477ec645530632/main.py#L34C32-L34C47

**Comment by SamirXR** [comment]
Nope, Recheck : 
![image](https://github.com/SamirXR/Nyx-Bot/assets/66723516/d94d75e6-bf89-4484-9428-72e494ed6bb6)
